Revert "selinux: clarify task subjective and objective credentials"
This reverts commit 5b26496c48e49f16e2cc247aec1e2491a53f6bd0.

This patch was cherry-picked into this kernel version to address a CVE.
Unfortunately, this patch breaks X86_64 build:

security/selinux/hooks.c: In function ‘selinux_binder_transaction’:
security/selinux/hooks.c:2062:32: error: passing argument 1 of
‘task_sid_binder’ from incompatible pointer type [-Werror=incompatible-pointer-types]
     u32 fromsid = task_sid_binder(from);
                                    ^~~~
security/selinux/hooks.c:261:19: note: expected ‘const struct task_struct *’
but argument is of type ‘const struct cred *’
     static inline u32 task_sid_binder(const struct task_struct *task)
                       ^~~~~~~~~~~~~~~

Reverting patch because it does not apply.

Signed-off-by: Dinh Nguyen <dinh.nguyen@intel.com>