FogBugz #229601: newhaven lcd: fix kbuild test robot warnings
The kbuild test robot noticed some problems with the newhaven
lcd driver.

1. lcd_of_match is not NULL terminated at line 606

2. Use ARRAY_SIZE instead of dividing sizeof array with sizeof an element

3. Random config test warnings:
   drivers/built-in.o: In function `brightness_store':
>> newhaven_lcd.c:(.text+0xd2225): undefined reference to
  `i2c_master_send'
   drivers/built-in.o: In function `lcd_init':
>> newhaven_lcd.c:(.init.text+0x8a9e): undefined reference to
   `i2c_register_driver'
   drivers/built-in.o: In function `lcd_exit':
>> newhaven_lcd.c:(.exit.text+0x439): undefined reference to
   `i2c_del_driver'
   drivers/built-in.o: In function `lcd_remove':
>> newhaven_lcd.c:(.exit.text+0x462): undefined reference to
   `i2c_master_send'

This patch squashes the two patches they kindly sent us plus adds
a Kconfig fix for the warnings in #3 above.

Signed-off-by: Fengguang Wu <fengguang.wu@intel.com>
Signed-off-by: Alan Tull <atull@opensource.altera.com>